-- =====================================================
-- QUEST APP - COMPLETE CALENDAR & AGENDA SYSTEM
-- Internal calendar with optional external sync
-- IA controls, Free vs Premium limits
-- =====================================================

-- =====================================================
-- 1. INTERNAL CALENDAR EVENTS (No external dependency)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.calendar_events (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  
  -- Basic info
  title TEXT NOT NULL,
  description TEXT,
  
  -- Time
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  is_all_day BOOLEAN DEFAULT false,
  
  -- Recurrence
  is_recurring BOOLEAN DEFAULT false,
  recurrence_rule TEXT, -- 'daily', 'weekly', 'monthly', 'weekdays'
  recurrence_end_date DATE,
  parent_event_id UUID REFERENCES public.calendar_events(id) ON DELETE CASCADE,
  
  -- Categorization
  event_type TEXT DEFAULT 'personal' CHECK (event_type IN ('personal', 'work', 'social', 'health', 'other')),
  color TEXT DEFAULT '#6366F1',
  icon TEXT DEFAULT '📅',
  
  -- Location (optional)
  location TEXT,
  
  -- Reminders
  reminder_minutes INTEGER[] DEFAULT ARRAY[10, 30],
  
  -- Source
  source TEXT DEFAULT 'manual' CHECK (source IN ('manual', 'ai_generated', 'synced_google', 'synced_apple')),
  external_id TEXT, -- For synced events
  
  -- Status
  status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 2. DAILY AGENDA ITEMS - Unified view of the day
-- =====================================================
CREATE TABLE IF NOT EXISTS public.daily_agenda_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  
  -- Date and time
  agenda_date DATE NOT NULL DEFAULT CURRENT_DATE,
  start_time TIME,
  end_time TIME,
  is_all_day BOOLEAN DEFAULT false,
  
  -- Item type
  item_type TEXT NOT NULL CHECK (item_type IN ('habit', 'quest', 'event', 'blocked')),
  
  -- References
  habit_id UUID REFERENCES public.habits(id) ON DELETE CASCADE,
  quest_id UUID,
  event_id UUID REFERENCES public.calendar_events(id) ON DELETE CASCADE,
  
  -- Display info
  title TEXT NOT NULL,
  description TEXT,
  icon TEXT DEFAULT '📌',
  color TEXT DEFAULT '#6B7280',
  pillar_id TEXT,
  
  -- Status
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped', 'rescheduled')),
  completed_at TIMESTAMPTZ,
  
  -- Priority (1 = highest)
  priority INTEGER DEFAULT 5,
  duration_minutes INTEGER DEFAULT 15,
  
  -- Source
  created_by TEXT DEFAULT 'manual' CHECK (created_by IN ('manual', 'ai_generated', 'system')),
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 3. AI DAILY QUESTS - Generated by AI each day
-- =====================================================
CREATE TABLE IF NOT EXISTS public.ai_daily_quests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  
  quest_date DATE NOT NULL DEFAULT CURRENT_DATE,
  
  -- Quest info
  title TEXT NOT NULL,
  description TEXT,
  icon TEXT DEFAULT '⚡',
  
  -- Categorization
  pillar_id TEXT REFERENCES public.pillars(id),
  difficulty TEXT DEFAULT 'medium' CHECK (difficulty IN ('easy', 'medium', 'hard')),
  
  -- Rewards
  xp_reward INTEGER DEFAULT 50,
  coin_reward INTEGER DEFAULT 10,
  
  -- Time
  estimated_minutes INTEGER DEFAULT 15,
  suggested_time TEXT, -- 'morning', 'afternoon', 'evening', 'anytime'
  
  -- Status
  status TEXT DEFAULT 'available' CHECK (status IN ('available', 'accepted', 'completed', 'skipped', 'expired')),
  completed_at TIMESTAMPTZ,
  
  -- Generation info
  generation_reason TEXT, -- Why AI suggested this
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 4. USER PREMIUM STATUS & DEVELOPER FLAG
-- =====================================================
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS is_premium BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS premium_expires_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS is_developer BOOLEAN DEFAULT false, -- Always premium
ADD COLUMN IF NOT EXISTS ai_calendar_uses_today INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ai_calendar_last_reset DATE,
ADD COLUMN IF NOT EXISTS daily_quest_creates_today INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS daily_quest_creates_last_reset DATE,
ADD COLUMN IF NOT EXISTS preferred_daily_quests INTEGER DEFAULT 5; -- 1-10

-- =====================================================
-- 5. FUNCTION: Check if user has premium access
-- =====================================================
CREATE OR REPLACE FUNCTION has_premium_access(p_user_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
  v_profile public.profiles%ROWTYPE;
BEGIN
  SELECT * INTO v_profile FROM public.profiles WHERE id = p_user_id;
  
  IF v_profile IS NULL THEN
    RETURN false;
  END IF;
  
  -- Developers always have premium
  IF v_profile.is_developer = true THEN
    RETURN true;
  END IF;
  
  -- Check premium status
  IF v_profile.is_premium = true AND 
     (v_profile.premium_expires_at IS NULL OR v_profile.premium_expires_at > NOW()) THEN
    RETURN true;
  END IF;
  
  RETURN false;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 6. FUNCTION: Set developer status (run once for yourself)
-- =====================================================
CREATE OR REPLACE FUNCTION set_developer_status(p_email TEXT)
RETURNS JSON AS $$
DECLARE
  v_user_id UUID;
BEGIN
  -- Find user by email in auth.users
  SELECT id INTO v_user_id
  FROM auth.users
  WHERE email = p_email;
  
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'User not found');
  END IF;
  
  -- Update profile
  UPDATE public.profiles
  SET is_developer = true, is_premium = true
  WHERE id = v_user_id;
  
  RETURN json_build_object(
    'success', true,
    'user_id', v_user_id,
    'message', 'Developer status granted - permanent premium access'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 7. FUNCTION: Check and use AI calendar action
-- =====================================================
CREATE OR REPLACE FUNCTION use_ai_calendar_action(p_user_id UUID)
RETURNS JSON AS $$
DECLARE
  v_profile public.profiles%ROWTYPE;
  v_is_premium BOOLEAN;
BEGIN
  SELECT * INTO v_profile FROM public.profiles WHERE id = p_user_id;
  v_is_premium := has_premium_access(p_user_id);
  
  -- Reset counter if new day
  IF v_profile.ai_calendar_last_reset IS NULL OR 
     v_profile.ai_calendar_last_reset < CURRENT_DATE THEN
    UPDATE public.profiles
    SET ai_calendar_uses_today = 0, ai_calendar_last_reset = CURRENT_DATE
    WHERE id = p_user_id;
    
    v_profile.ai_calendar_uses_today := 0;
  END IF;
  
  -- Premium users have unlimited
  IF v_is_premium THEN
    UPDATE public.profiles
    SET ai_calendar_uses_today = ai_calendar_uses_today + 1
    WHERE id = p_user_id;
    
    RETURN json_build_object(
      'allowed', true,
      'is_premium', true,
      'uses_today', v_profile.ai_calendar_uses_today + 1,
      'limit', 'unlimited'
    );
  END IF;
  
  -- Free users: 1 per day
  IF v_profile.ai_calendar_uses_today >= 1 THEN
    RETURN json_build_object(
      'allowed', false,
      'is_premium', false,
      'uses_today', v_profile.ai_calendar_uses_today,
      'limit', 1,
      'message', 'Ya usaste tu ayuda de IA del día. Actualiza a Premium para acceso ilimitado.'
    );
  END IF;
  
  UPDATE public.profiles
  SET ai_calendar_uses_today = ai_calendar_uses_today + 1
  WHERE id = p_user_id;
  
  RETURN json_build_object(
    'allowed', true,
    'is_premium', false,
    'uses_today', v_profile.ai_calendar_uses_today + 1,
    'limit', 1
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 8. FUNCTION: Check and use manual quest creation
-- =====================================================
CREATE OR REPLACE FUNCTION use_manual_quest_create(p_user_id UUID)
RETURNS JSON AS $$
DECLARE
  v_profile public.profiles%ROWTYPE;
  v_is_premium BOOLEAN;
BEGIN
  SELECT * INTO v_profile FROM public.profiles WHERE id = p_user_id;
  v_is_premium := has_premium_access(p_user_id);
  
  -- Reset counter if new day
  IF v_profile.daily_quest_creates_last_reset IS NULL OR 
     v_profile.daily_quest_creates_last_reset < CURRENT_DATE THEN
    UPDATE public.profiles
    SET daily_quest_creates_today = 0, daily_quest_creates_last_reset = CURRENT_DATE
    WHERE id = p_user_id;
    
    v_profile.daily_quest_creates_today := 0;
  END IF;
  
  -- Premium users have unlimited
  IF v_is_premium THEN
    UPDATE public.profiles
    SET daily_quest_creates_today = daily_quest_creates_today + 1
    WHERE id = p_user_id;
    
    RETURN json_build_object('allowed', true, 'is_premium', true);
  END IF;
  
  -- Free users: 10 per day
  IF v_profile.daily_quest_creates_today >= 10 THEN
    RETURN json_build_object(
      'allowed', false,
      'is_premium', false,
      'uses_today', v_profile.daily_quest_creates_today,
      'limit', 10,
      'message', 'Alcanzaste el límite de 10 quests diarias. Premium = ilimitadas.'
    );
  END IF;
  
  UPDATE public.profiles
  SET daily_quest_creates_today = daily_quest_creates_today + 1
  WHERE id = p_user_id;
  
  RETURN json_build_object('allowed', true, 'uses_today', v_profile.daily_quest_creates_today + 1);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 9. FUNCTION: Add calendar event
-- =====================================================
CREATE OR REPLACE FUNCTION add_calendar_event(
  p_user_id UUID,
  p_title TEXT,
  p_start_time TIMESTAMPTZ,
  p_end_time TIMESTAMPTZ,
  p_description TEXT DEFAULT NULL,
  p_event_type TEXT DEFAULT 'personal',
  p_is_recurring BOOLEAN DEFAULT false,
  p_recurrence_rule TEXT DEFAULT NULL,
  p_color TEXT DEFAULT '#6366F1',
  p_source TEXT DEFAULT 'manual'
)
RETURNS JSON AS $$
DECLARE
  v_event_id UUID;
BEGIN
  INSERT INTO public.calendar_events (
    user_id, title, description, start_time, end_time,
    event_type, is_recurring, recurrence_rule, color, source
  )
  VALUES (
    p_user_id, p_title, p_description, p_start_time, p_end_time,
    p_event_type, p_is_recurring, p_recurrence_rule, p_color, p_source
  )
  RETURNING id INTO v_event_id;
  
  RETURN json_build_object(
    'success', true,
    'event_id', v_event_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 10. FUNCTION: Get calendar events for date range
-- =====================================================
CREATE OR REPLACE FUNCTION get_calendar_events(
  p_user_id UUID,
  p_start_date DATE,
  p_end_date DATE
)
RETURNS TABLE (
  id UUID,
  title TEXT,
  description TEXT,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  is_all_day BOOLEAN,
  event_type TEXT,
  color TEXT,
  icon TEXT,
  status TEXT,
  source TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    e.id, e.title, e.description,
    e.start_time, e.end_time, e.is_all_day,
    e.event_type, e.color, e.icon, e.status, e.source
  FROM public.calendar_events e
  WHERE e.user_id = p_user_id
    AND e.start_time::date >= p_start_date
    AND e.start_time::date <= p_end_date
    AND e.status != 'cancelled'
  ORDER BY e.start_time;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 11. FUNCTION: Generate daily agenda
-- =====================================================
CREATE OR REPLACE FUNCTION generate_daily_agenda(
  p_user_id UUID,
  p_date DATE DEFAULT CURRENT_DATE
)
RETURNS TABLE (
  id UUID,
  start_time TIME,
  end_time TIME,
  item_type TEXT,
  title TEXT,
  description TEXT,
  icon TEXT,
  color TEXT,
  pillar_id TEXT,
  status TEXT,
  duration_minutes INTEGER,
  priority INTEGER,
  reference_id UUID
) AS $$
BEGIN
  -- Clear and regenerate agenda for this day
  DELETE FROM public.daily_agenda_items
  WHERE user_id = p_user_id AND agenda_date = p_date;
  
  -- Insert habits
  INSERT INTO public.daily_agenda_items (
    user_id, agenda_date, start_time, item_type, habit_id,
    title, description, icon, color, pillar_id, status, priority, duration_minutes, created_by
  )
  SELECT 
    p_user_id, p_date, h.preferred_time, 'habit', h.id,
    h.title, h.description, h.icon,
    COALESCE(p.color, '#10B981'), h.pillar_id,
    CASE WHEN hl.id IS NOT NULL THEN 'completed' ELSE 'pending' END,
    CASE h.time_of_day
      WHEN 'morning' THEN 1
      WHEN 'afternoon' THEN 2
      WHEN 'evening' THEN 3
      ELSE 4
    END,
    15, 'system'
  FROM public.habits h
  LEFT JOIN public.pillars p ON p.id = h.pillar_id
  LEFT JOIN public.habit_logs hl ON hl.habit_id = h.id AND hl.log_date = p_date
  WHERE h.user_id = p_user_id AND h.is_active = true
    AND (h.frequency = 'daily' 
      OR (h.frequency = 'specific_days' AND LOWER(trim(to_char(p_date, 'day'))) = ANY(h.frequency_days)));
  
  -- Insert calendar events
  INSERT INTO public.daily_agenda_items (
    user_id, agenda_date, start_time, end_time, item_type, event_id,
    title, description, icon, color, status, priority, duration_minutes, created_by
  )
  SELECT 
    p_user_id, p_date, e.start_time::time, e.end_time::time, 'event', e.id,
    e.title, e.description, e.icon, e.color, 'pending', 2,
    EXTRACT(EPOCH FROM (e.end_time - e.start_time)) / 60,
    CASE e.source WHEN 'ai_generated' THEN 'ai_generated' ELSE 'manual' END
  FROM public.calendar_events e
  WHERE e.user_id = p_user_id
    AND e.start_time::date = p_date
    AND e.status = 'scheduled';
  
  -- Insert AI daily quests that were accepted
  INSERT INTO public.daily_agenda_items (
    user_id, agenda_date, item_type, quest_id,
    title, description, icon, color, pillar_id, status, priority, duration_minutes, created_by
  )
  SELECT 
    p_user_id, p_date, 'quest', q.id,
    q.title, q.description, q.icon,
    COALESCE(pl.color, '#F59E0B'), q.pillar_id,
    CASE WHEN q.status = 'completed' THEN 'completed' ELSE 'pending' END,
    3, q.estimated_minutes, 'ai_generated'
  FROM public.ai_daily_quests q
  LEFT JOIN public.pillars pl ON pl.id = q.pillar_id
  WHERE q.user_id = p_user_id
    AND q.quest_date = p_date
    AND q.status IN ('accepted', 'completed');
  
  -- Return the agenda
  RETURN QUERY
  SELECT 
    dai.id, dai.start_time, dai.end_time, dai.item_type,
    dai.title, dai.description, dai.icon, dai.color,
    dai.pillar_id, dai.status, dai.duration_minutes, dai.priority,
    COALESCE(dai.habit_id, dai.quest_id, dai.event_id)
  FROM public.daily_agenda_items dai
  WHERE dai.user_id = p_user_id AND dai.agenda_date = p_date
  ORDER BY dai.priority, dai.start_time NULLS LAST;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 12. FUNCTION: Get weekly calendar view
-- =====================================================
CREATE OR REPLACE FUNCTION get_weekly_calendar(
  p_user_id UUID,
  p_week_start DATE DEFAULT NULL
)
RETURNS JSON AS $$
DECLARE
  v_start DATE;
  v_end DATE;
  v_days JSON[];
  v_day DATE;
  v_day_data JSON;
BEGIN
  -- Default to current week (Monday start)
  IF p_week_start IS NULL THEN
    v_start := date_trunc('week', CURRENT_DATE)::date;
  ELSE
    v_start := p_week_start;
  END IF;
  v_end := v_start + INTERVAL '6 days';
  
  -- Build array for each day
  FOR v_day IN SELECT generate_series(v_start, v_end, '1 day'::interval)::date
  LOOP
    SELECT json_build_object(
      'date', v_day,
      'day_name', to_char(v_day, 'Dy'),
      'habits_count', (SELECT COUNT(*) FROM public.habits h 
        WHERE h.user_id = p_user_id AND h.is_active = true),
      'habits_completed', (SELECT COUNT(*) FROM public.habit_logs hl 
        JOIN public.habits h ON h.id = hl.habit_id
        WHERE h.user_id = p_user_id AND hl.log_date = v_day),
      'events_count', (SELECT COUNT(*) FROM public.calendar_events e 
        WHERE e.user_id = p_user_id AND e.start_time::date = v_day AND e.status = 'scheduled'),
      'quests_count', (SELECT COUNT(*) FROM public.ai_daily_quests q 
        WHERE q.user_id = p_user_id AND q.quest_date = v_day AND q.status IN ('accepted', 'available'))
    ) INTO v_day_data;
    
    v_days := array_append(v_days, v_day_data);
  END LOOP;
  
  RETURN json_build_object(
    'week_start', v_start,
    'week_end', v_end,
    'days', v_days
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 13. FUNCTION: Get monthly calendar view
-- =====================================================
CREATE OR REPLACE FUNCTION get_monthly_calendar(
  p_user_id UUID,
  p_year INTEGER DEFAULT NULL,
  p_month INTEGER DEFAULT NULL
)
RETURNS JSON AS $$
DECLARE
  v_start DATE;
  v_end DATE;
  v_days JSON[];
  v_day DATE;
  v_day_data JSON;
BEGIN
  -- Default to current month
  IF p_year IS NULL THEN
    p_year := EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER;
  END IF;
  IF p_month IS NULL THEN
    p_month := EXTRACT(MONTH FROM CURRENT_DATE)::INTEGER;
  END IF;
  
  v_start := make_date(p_year, p_month, 1);
  v_end := (v_start + INTERVAL '1 month - 1 day')::date;
  
  -- Build array for each day (simplified for month view)
  FOR v_day IN SELECT generate_series(v_start, v_end, '1 day'::interval)::date
  LOOP
    SELECT json_build_object(
      'date', v_day,
      'day', EXTRACT(DAY FROM v_day),
      'has_habits', (SELECT COUNT(*) > 0 FROM public.habit_logs hl 
        JOIN public.habits h ON h.id = hl.habit_id
        WHERE h.user_id = p_user_id AND hl.log_date = v_day),
      'has_events', (SELECT COUNT(*) > 0 FROM public.calendar_events e 
        WHERE e.user_id = p_user_id AND e.start_time::date = v_day),
      'completion_rate', (
        SELECT CASE WHEN habit_count > 0 
          THEN ROUND((completed_count::decimal / habit_count) * 100)
          ELSE 0 END
        FROM (
          SELECT 
            COUNT(*) FILTER (WHERE hl.id IS NOT NULL) as completed_count,
            COUNT(*) as habit_count
          FROM public.habits h
          LEFT JOIN public.habit_logs hl ON hl.habit_id = h.id AND hl.log_date = v_day
          WHERE h.user_id = p_user_id AND h.is_active = true
        ) sub
      )
    ) INTO v_day_data;
    
    v_days := array_append(v_days, v_day_data);
  END LOOP;
  
  RETURN json_build_object(
    'year', p_year,
    'month', p_month,
    'month_name', to_char(v_start, 'Month'),
    'days_in_month', EXTRACT(DAY FROM v_end),
    'first_day_weekday', EXTRACT(DOW FROM v_start),
    'days', v_days
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 14. FUNCTION: Generate AI daily quests
-- =====================================================
CREATE OR REPLACE FUNCTION generate_ai_daily_quests(
  p_user_id UUID,
  p_date DATE DEFAULT CURRENT_DATE,
  p_count INTEGER DEFAULT NULL
)
RETURNS JSON AS $$
DECLARE
  v_profile public.profiles%ROWTYPE;
  v_quest_count INTEGER;
  v_pillars TEXT[];
  v_class TEXT;
  v_inserted INTEGER := 0;
  v_pillar TEXT;
  v_quest_templates JSON[] := ARRAY[
    -- Physical
    '{"pillar": "physical", "title_es": "Camina 5,000 pasos", "title_en": "Walk 5,000 steps", "icon": "🚶", "difficulty": "easy", "xp": 30}'::json,
    '{"pillar": "physical", "title_es": "Haz 20 flexiones", "title_en": "Do 20 push-ups", "icon": "💪", "difficulty": "medium", "xp": 50}'::json,
    '{"pillar": "physical", "title_es": "Mantén una plancha 60 segundos", "title_en": "Hold a plank for 60 seconds", "icon": "🏋️", "difficulty": "medium", "xp": 50}'::json,
    '{"pillar": "physical", "title_es": "Toma 8 vasos de agua", "title_en": "Drink 8 glasses of water", "icon": "💧", "difficulty": "easy", "xp": 25}'::json,
    '{"pillar": "physical", "title_es": "Estira por 10 minutos", "title_en": "Stretch for 10 minutes", "icon": "🧘", "difficulty": "easy", "xp": 25}'::json,
    
    -- Mental
    '{"pillar": "mental", "title_es": "Lee 10 páginas de un libro", "title_en": "Read 10 pages of a book", "icon": "📚", "difficulty": "easy", "xp": 30}'::json,
    '{"pillar": "mental", "title_es": "Aprende 5 palabras nuevas en otro idioma", "title_en": "Learn 5 new words in another language", "icon": "🗣️", "difficulty": "medium", "xp": 40}'::json,
    '{"pillar": "mental", "title_es": "Completa un puzzle o sudoku", "title_en": "Complete a puzzle or sudoku", "icon": "🧩", "difficulty": "medium", "xp": 35}'::json,
    '{"pillar": "mental", "title_es": "Medita 10 minutos", "title_en": "Meditate for 10 minutes", "icon": "🧘‍♂️", "difficulty": "easy", "xp": 30}'::json,
    
    -- Spiritual
    '{"pillar": "spiritual", "title_es": "Escribe 3 cosas por las que estás agradecido", "title_en": "Write 3 things you are grateful for", "icon": "🙏", "difficulty": "easy", "xp": 25}'::json,
    '{"pillar": "spiritual", "title_es": "Practica respiración profunda 5 minutos", "title_en": "Practice deep breathing for 5 minutes", "icon": "🌬️", "difficulty": "easy", "xp": 20}'::json,
    '{"pillar": "spiritual", "title_es": "Reflexiona sobre tu día en un diario", "title_en": "Reflect on your day in a journal", "icon": "📝", "difficulty": "medium", "xp": 40}'::json,
    
    -- Social
    '{"pillar": "social", "title_es": "Envía un mensaje a un amigo que no has contactado", "title_en": "Send a message to a friend you have not contacted", "icon": "💬", "difficulty": "easy", "xp": 25}'::json,
    '{"pillar": "social", "title_es": "Haz un cumplido sincero a alguien", "title_en": "Give a sincere compliment to someone", "icon": "😊", "difficulty": "easy", "xp": 20}'::json,
    '{"pillar": "social", "title_es": "Llama a un familiar", "title_en": "Call a family member", "icon": "📞", "difficulty": "medium", "xp": 35}'::json,
    
    -- Creative
    '{"pillar": "creative", "title_es": "Dibuja algo durante 15 minutos", "title_en": "Draw something for 15 minutes", "icon": "🎨", "difficulty": "medium", "xp": 40}'::json,
    '{"pillar": "creative", "title_es": "Escribe una página de lo que sea", "title_en": "Write one page of anything", "icon": "✍️", "difficulty": "medium", "xp": 45}'::json,
    '{"pillar": "creative", "title_es": "Toma 5 fotos creativas", "title_en": "Take 5 creative photos", "icon": "📸", "difficulty": "easy", "xp": 30}'::json,
    
    -- Professional
    '{"pillar": "professional", "title_es": "Organiza tu espacio de trabajo", "title_en": "Organize your workspace", "icon": "🗂️", "difficulty": "easy", "xp": 25}'::json,
    '{"pillar": "professional", "title_es": "Aprende algo nuevo de tu profesión", "title_en": "Learn something new about your profession", "icon": "💼", "difficulty": "medium", "xp": 50}'::json,
    '{"pillar": "professional", "title_es": "Revisa y actualiza tu lista de tareas", "title_en": "Review and update your task list", "icon": "📋", "difficulty": "easy", "xp": 20}'::json,
    
    -- Self-Care
    '{"pillar": "self_care", "title_es": "Haz tu rutina de skincare completa", "title_en": "Do your complete skincare routine", "icon": "🧴", "difficulty": "easy", "xp": 25}'::json,
    '{"pillar": "self_care", "title_es": "Ordena tu habitación", "title_en": "Tidy up your room", "icon": "🧹", "difficulty": "easy", "xp": 25}'::json,
    '{"pillar": "self_care", "title_es": "Prepara una comida saludable", "title_en": "Prepare a healthy meal", "icon": "🥗", "difficulty": "medium", "xp": 35}'::json
  ]::json[];
  v_template JSON;
  v_random_indices INTEGER[];
  v_idx INTEGER;
BEGIN
  SELECT * INTO v_profile FROM public.profiles WHERE id = p_user_id;
  
  IF v_profile IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'User not found');
  END IF;
  
  -- Determine quest count
  v_quest_count := COALESCE(p_count, v_profile.preferred_daily_quests, 5);
  
  -- Delete existing quests for this day that haven't been accepted
  DELETE FROM public.ai_daily_quests
  WHERE user_id = p_user_id 
    AND quest_date = p_date 
    AND status = 'available';
  
  -- Get user pillars and class for personalization
  v_pillars := COALESCE(v_profile.selected_pillars, ARRAY['physical', 'mental', 'self_care']);
  v_class := v_profile.character_class;
  
  -- Generate random quests
  -- In real implementation, this would use AI to personalize
  -- For now, we select randomly from templates matching user's pillars
  
  FOR i IN 1..v_quest_count LOOP
    -- Pick random template
    v_idx := floor(random() * array_length(v_quest_templates, 1) + 1)::integer;
    v_template := v_quest_templates[v_idx];
    
    -- Insert quest
    INSERT INTO public.ai_daily_quests (
      user_id, quest_date, title, description, icon, pillar_id,
      difficulty, xp_reward, coin_reward, estimated_minutes, suggested_time,
      generation_reason
    )
    VALUES (
      p_user_id,
      p_date,
      v_template ->> 'title_es', -- Use Spanish for now, could check language preference
      NULL,
      v_template ->> 'icon',
      v_template ->> 'pillar',
      v_template ->> 'difficulty',
      (v_template ->> 'xp')::integer,
      ((v_template ->> 'xp')::integer / 5),
      15,
      CASE floor(random() * 4)::integer
        WHEN 0 THEN 'morning'
        WHEN 1 THEN 'afternoon'
        WHEN 2 THEN 'evening'
        ELSE 'anytime'
      END,
      'AI generated based on your pillars and class'
    );
    
    v_inserted := v_inserted + 1;
  END LOOP;
  
  RETURN json_build_object(
    'success', true,
    'quests_generated', v_inserted,
    'date', p_date
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 15. FUNCTION: Accept or skip AI quest
-- =====================================================
CREATE OR REPLACE FUNCTION respond_to_ai_quest(
  p_user_id UUID,
  p_quest_id UUID,
  p_action TEXT -- 'accept', 'skip', 'complete'
)
RETURNS JSON AS $$
DECLARE
  v_quest public.ai_daily_quests%ROWTYPE;
BEGIN
  SELECT * INTO v_quest 
  FROM public.ai_daily_quests 
  WHERE id = p_quest_id AND user_id = p_user_id;
  
  IF v_quest IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Quest not found');
  END IF;
  
  IF p_action = 'accept' THEN
    UPDATE public.ai_daily_quests
    SET status = 'accepted'
    WHERE id = p_quest_id;
    
  ELSIF p_action = 'skip' THEN
    UPDATE public.ai_daily_quests
    SET status = 'skipped'
    WHERE id = p_quest_id;
    
  ELSIF p_action = 'complete' THEN
    UPDATE public.ai_daily_quests
    SET status = 'completed', completed_at = NOW()
    WHERE id = p_quest_id;
    
    -- Award XP and coins
    UPDATE public.profiles
    SET 
      total_xp = total_xp + v_quest.xp_reward,
      quest_coins = quest_coins + v_quest.coin_reward
    WHERE id = p_user_id;
    
    RETURN json_build_object(
      'success', true,
      'action', 'completed',
      'xp_earned', v_quest.xp_reward,
      'coins_earned', v_quest.coin_reward
    );
  END IF;
  
  RETURN json_build_object('success', true, 'action', p_action);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 16. FUNCTION: Get today's AI quests
-- =====================================================
CREATE OR REPLACE FUNCTION get_ai_daily_quests(
  p_user_id UUID,
  p_date DATE DEFAULT CURRENT_DATE
)
RETURNS TABLE (
  id UUID,
  title TEXT,
  description TEXT,
  icon TEXT,
  pillar_id TEXT,
  difficulty TEXT,
  xp_reward INTEGER,
  coin_reward INTEGER,
  estimated_minutes INTEGER,
  suggested_time TEXT,
  status TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    q.id, q.title, q.description, q.icon, q.pillar_id,
    q.difficulty, q.xp_reward, q.coin_reward,
    q.estimated_minutes, q.suggested_time, q.status
  FROM public.ai_daily_quests q
  WHERE q.user_id = p_user_id
    AND q.quest_date = p_date
    AND q.status != 'expired'
  ORDER BY 
    CASE q.status
      WHEN 'available' THEN 1
      WHEN 'accepted' THEN 2
      WHEN 'completed' THEN 3
      ELSE 4
    END,
    q.created_at;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 17. FUNCTION: Complete agenda item
-- =====================================================
CREATE OR REPLACE FUNCTION complete_agenda_item(
  p_user_id UUID,
  p_item_id UUID
)
RETURNS JSON AS $$
DECLARE
  v_item public.daily_agenda_items%ROWTYPE;
  v_result JSON;
BEGIN
  SELECT * INTO v_item
  FROM public.daily_agenda_items
  WHERE id = p_item_id AND user_id = p_user_id;
  
  IF v_item IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Item not found');
  END IF;
  
  -- Handle based on type
  IF v_item.item_type = 'habit' AND v_item.habit_id IS NOT NULL THEN
    v_result := complete_habit(v_item.habit_id, p_user_id, NULL, NULL);
    
  ELSIF v_item.item_type = 'quest' AND v_item.quest_id IS NOT NULL THEN
    v_result := respond_to_ai_quest(p_user_id, v_item.quest_id, 'complete');
    
  ELSIF v_item.item_type = 'event' AND v_item.event_id IS NOT NULL THEN
    UPDATE public.calendar_events
    SET status = 'completed'
    WHERE id = v_item.event_id;
    v_result := json_build_object('success', true, 'type', 'event');
  END IF;
  
  -- Update agenda item
  UPDATE public.daily_agenda_items
  SET status = 'completed', completed_at = NOW(), updated_at = NOW()
  WHERE id = p_item_id;
  
  RETURN json_build_object(
    'success', true,
    'item_type', v_item.item_type,
    'result', v_result
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 18. FUNCTION: Get agenda summary
-- =====================================================
CREATE OR REPLACE FUNCTION get_agenda_summary(
  p_user_id UUID,
  p_date DATE DEFAULT CURRENT_DATE
)
RETURNS JSON AS $$
DECLARE
  v_total INTEGER;
  v_completed INTEGER;
  v_habits_total INTEGER;
  v_habits_completed INTEGER;
  v_quests_total INTEGER;
  v_quests_completed INTEGER;
  v_events_total INTEGER;
BEGIN
  SELECT 
    COUNT(*),
    COUNT(*) FILTER (WHERE status = 'completed')
  INTO v_total, v_completed
  FROM public.daily_agenda_items
  WHERE user_id = p_user_id AND agenda_date = p_date;
  
  SELECT 
    COUNT(*),
    COUNT(*) FILTER (WHERE status = 'completed')
  INTO v_habits_total, v_habits_completed
  FROM public.daily_agenda_items
  WHERE user_id = p_user_id AND agenda_date = p_date AND item_type = 'habit';
  
  SELECT 
    COUNT(*),
    COUNT(*) FILTER (WHERE status = 'completed')
  INTO v_quests_total, v_quests_completed
  FROM public.daily_agenda_items
  WHERE user_id = p_user_id AND agenda_date = p_date AND item_type = 'quest';
  
  SELECT COUNT(*) INTO v_events_total
  FROM public.daily_agenda_items
  WHERE user_id = p_user_id AND agenda_date = p_date AND item_type = 'event';
  
  RETURN json_build_object(
    'date', p_date,
    'total_items', v_total,
    'completed', v_completed,
    'progress_percentage', CASE WHEN v_total > 0 THEN ROUND((v_completed::decimal / v_total) * 100) ELSE 0 END,
    'habits', json_build_object('total', v_habits_total, 'completed', v_habits_completed),
    'quests', json_build_object('total', v_quests_total, 'completed', v_quests_completed),
    'events', json_build_object('total', v_events_total)
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- 19. RLS POLICIES
-- =====================================================
ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_agenda_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_daily_quests ENABLE ROW LEVEL SECURITY;

-- Calendar events
DROP POLICY IF EXISTS "Users manage own calendar events" ON public.calendar_events;
CREATE POLICY "Users manage own calendar events" ON public.calendar_events
FOR ALL USING (auth.uid() = user_id);

-- Daily agenda
DROP POLICY IF EXISTS "Users manage own agenda" ON public.daily_agenda_items;
CREATE POLICY "Users manage own agenda" ON public.daily_agenda_items
FOR ALL USING (auth.uid() = user_id);

-- AI quests
DROP POLICY IF EXISTS "Users manage own ai quests" ON public.ai_daily_quests;
CREATE POLICY "Users manage own ai quests" ON public.ai_daily_quests
FOR ALL USING (auth.uid() = user_id);

-- =====================================================
-- 20. INDEXES
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_calendar_events_user_date ON public.calendar_events(user_id, start_time);
CREATE INDEX IF NOT EXISTS idx_daily_agenda_user_date ON public.daily_agenda_items(user_id, agenda_date);
CREATE INDEX IF NOT EXISTS idx_ai_quests_user_date ON public.ai_daily_quests(user_id, quest_date);

-- =====================================================
-- INSTRUCTIONS TO SET YOURSELF AS DEVELOPER:
-- Run this query with your email after deploying:
-- SELECT set_developer_status('your-email@example.com');
-- =====================================================
