-- 💪 FÍSICO (10)
INSERT INTO assessment_questions (pillar, question_text, question_text_en, question_type, options, options_en, weight, sort_order) VALUES
('physical', '¿Con qué frecuencia haces ejercicio?', 'How often do you exercise?', 'single_choice', '["Nunca", "1-2 veces al mes", "1-2 veces por semana", "3-4 veces por semana", "5+ veces por semana"]', '["Never", "1-2 times a month", "1-2 times a week", "3-4 times a week", "5+ times a week"]', 3, 1),
('physical', '¿Qué tipo de ejercicio prefieres?', 'What type of exercise do you prefer?', 'multiple_choice', '["Gimnasio/Pesas", "Cardio (correr, nadar)", "Deportes de equipo", "Yoga/Pilates", "Calistenia", "Ninguno todavía"]', '["Gym/Weights", "Cardio (running, swimming)", "Team sports", "Yoga/Pilates", "Calisthenics", "None yet"]', 1, 2),
('physical', '¿Cómo calificarías tu alimentación actual?', 'How would you rate your current diet?', 'slider', null, null, 2, 3),
('physical', '¿Cuántas horas duermes en promedio por noche?', 'How many hours do you sleep on average per night?', 'single_choice', '["Menos de 5", "5-6 horas", "6-7 horas", "7-8 horas", "Más de 8"]', '["Less than 5", "5-6 hours", "6-7 hours", "7-8 hours", "More than 8"]', 2, 4),
('physical', '¿Cuántos vasos de agua bebes al día?', 'How many glasses of water do you drink per day?', 'single_choice', '["0-2", "3-4", "5-6", "7-8", "9+"]', '["0-2", "3-4", "5-6", "7-8", "9+"]', 1, 5),
('physical', '¿Cómo te sientes físicamente en general?', 'How do you feel physically overall?', 'slider', null, null, 2, 6),
('physical', '¿Cuáles son tus principales obstáculos para estar más activo?', 'What are your main obstacles to being more active?', 'multiple_choice', '["Falta de tiempo", "Falta de motivación", "No sé por dónde empezar", "Lesiones/dolor", "Costo de gimnasio", "Ninguno"]', '["Lack of time", "Lack of motivation", "Don''t know where to start", "Injuries/pain", "Gym cost", "None"]', 2, 7),
('physical', '¿Cómo calificarías tu rutina de cuidado personal?', 'How would you rate your personal care routine?', 'single_choice', '["No tengo rutina", "Básica (lo mínimo)", "Regular (ducha, dientes)", "Buena (incluyo skincare)", "Excelente (rutina completa)"]', '["No routine", "Basic (minimum)", "Regular (shower, teeth)", "Good (include skincare)", "Excellent (complete routine)"]', 2, 8),
('physical', '¿Qué aspectos te gustaría mejorar?', 'Which aspects would you like to improve?', 'multiple_choice', '["Cuidado de piel", "Cuidado del cabello", "Higiene dental", "Vestimenta", "Postura", "Hidratación", "Nada"]', '["Skin care", "Hair care", "Dental hygiene", "Clothing", "Posture", "Hydration", "Nothing"]', 1, 9),
('physical', '¿Con qué frecuencia cuidas tu apariencia?', 'How often do you take care of your appearance?', 'single_choice', '["Casi nunca", "Solo ocasiones especiales", "Algunas veces/semana", "Casi todos los días", "Todos los días"]', '["Almost never", "Special occasions only", "A few times a week", "Almost every day", "Every day"]', 2, 10);

-- 🧠 MENTAL (7)
INSERT INTO assessment_questions (pillar, question_text, question_text_en, question_type, options, options_en, weight, sort_order) VALUES
('mental', '¿Con qué frecuencia lees o estudias?', 'How often do you read or study?', 'single_choice', '["Nunca", "Pocas veces al mes", "Una vez por semana", "Varias veces/semana", "Diariamente"]', '["Never", "Few times a month", "Once a week", "Several times/week", "Daily"]', 2, 11),
('mental', '¿Estás aprendiendo algo nuevo activamente?', 'Are you actively learning something new?', 'single_choice', '["No", "Lo intenté pero dejé", "Sí, ocasionalmente", "Sí, regularmente", "Sí, múltiples cosas"]', '["No", "Tried but quit", "Yes, occasionally", "Yes, regularly", "Yes, multiple things"]', 2, 12),
('mental', '¿Qué tan productivo te sientes?', 'How productive do you feel?', 'slider', null, null, 3, 13),
('mental', '¿Con qué frecuencia te distraes con redes sociales?', 'How often do you get distracted by social media?', 'single_choice', '["Todo el tiempo", "Muy frecuente", "A veces", "Raramente", "Casi nunca"]', '["All the time", "Very frequently", "Sometimes", "Rarely", "Almost never"]', 2, 14),
('mental', '¿Qué áreas te gustaría aprender?', 'What areas would you like to learn?', 'multiple_choice', '["Idiomas", "Programación", "Negocios", "Arte", "Ciencias", "Habilidades sociales", "Otro"]', '["Languages", "Programming", "Business", "Art", "Sciences", "Social skills", "Other"]', 1, 15),
('mental', '¿Cómo calificarías tu concentración?', 'How would you rate your concentration?', 'slider', null, null, 2, 16),
('mental', '¿Qué te impide ser más productivo?', 'What prevents you from being more productive?', 'multiple_choice', '["Procrastinación", "Falta de objetivos", "Distracciones", "Cansancio mental", "Demasiadas tareas", "Nada"]', '["Procrastination", "Lack of goals", "Distractions", "Mental fatigue", "Too many tasks", "Nothing"]', 2, 17);

-- ❤️ SOCIAL (6)
INSERT INTO assessment_questions (pillar, question_text, question_text_en, question_type, options, options_en, weight, sort_order) VALUES
('social', '¿Cómo te describes socialmente?', 'How would you describe yourself socially?', 'slider', null, null, 1, 18),
('social', '¿Con qué frecuencia sales con amigos?', 'How often do you go out with friends?', 'single_choice', '["Nunca o casi nunca", "Una vez al mes", "1-2 veces/semana", "3-4 veces/semana", "Casi todos los días"]', '["Never or almost never", "Once a month", "1-2 times/week", "3-4 times/week", "Almost every day"]', 2, 19),
('social', '¿Cuántos amigos cercanos tienes?', 'How many close friends do you have?', 'single_choice', '["0-1", "2-3", "4-6", "7-10", "Más de 10"]', '["0-1", "2-3", "4-6", "7-10", "More than 10"]', 2, 20),
('social', '¿Cómo es tu relación con tu familia?', 'How is your relationship with your family?', 'single_choice', '["Muy distante", "Algo distante", "Normal", "Cercana", "Muy cercana"]', '["Very distant", "Somewhat distant", "Normal", "Close", "Very close"]', 1, 21),
('social', '¿Disfrutas conocer gente nueva?', 'Do you enjoy meeting new people?', 'single_choice', '["Para nada", "No mucho", "Indiferente", "Sí, me gusta", "Me encanta"]', '["Not at all", "Not much", "Indifferent", "Yes, I like it", "I love it"]', 1, 22),
('social', '¿En qué áreas sociales mejorarías?', 'In which social areas would you improve?', 'multiple_choice', '["Hacer amigos", "Mantener amistades", "Hablar en público", "Ser más sociable", "Networking", "Ninguna"]', '["Making friends", "Maintaining friendships", "Public speaking", "Being more sociable", "Networking", "None"]', 2, 23);

-- 💼 PROFESIONAL (7)
INSERT INTO assessment_questions (pillar, question_text, question_text_en, question_type, options, options_en, weight, sort_order) VALUES
('professional', '¿Cuál es tu situación profesional?', 'What is your professional situation?', 'single_choice', '["Estudiante", "Empleado full-time", "Freelancer", "Emprendedor", "Desempleado", "Otro"]', '["Student", "Full-time employee", "Freelancer", "Entrepreneur", "Unemployed", "Other"]', 1, 24),
('professional', '¿Qué tan satisfecho estás profesionalmente?', 'How satisfied are you professionally?', 'slider', null, null, 3, 25),
('professional', '¿Tienes metas profesionales claras?', 'Do you have clear professional goals?', 'single_choice', '["No tengo idea", "Ideas vagas", "Ideas sin plan", "Metas claras", "Plan detallado"]', '["No idea", "Vague ideas", "Ideas no plan", "Clear goals", "Detailed plan"]', 2, 26),
('professional', '¿Cuánto tiempo dedicas a tu desarrollo?', 'How much time do you dedicate to your development?', 'single_choice', '["0 horas", "1-2 horas", "3-5 horas", "6-10 horas", "Más de 10"]', '["0 hours", "1-2 hours", "3-5 hours", "6-10 hours", "More than 10"]', 2, 27),
('professional', '¿Qué habilidades quieres desarrollar?', 'What skills do you want to develop?', 'multiple_choice', '["Liderazgo", "Comunicación", "Habilidades técnicas", "Ventas", "Finanzas", "Emprendimiento", "Gestión tiempo"]', '["Leadership", "Communication", "Technical skills", "Sales", "Finance", "Entrepreneurship", "Time management"]', 2, 28),
('professional', '¿Tienes sistema para gestionar finanzas?', 'Do you have a system to manage finances?', 'single_choice', '["No, ninguno", "Reviso ocasionalmente", "Sé cuánto gasto", "Presupuesto básico", "Presupuesto detallado"]', '["No, none", "Check occasionally", "Know how much I spend", "Basic budget", "Detailed budget"]', 2, 29),
('professional', '¿Qué te impide alcanzar tus metas?', 'What prevents you from reaching your goals?', 'multiple_choice', '["Falta experiencia", "Falta educación", "Falta oportunidades", "Miedo al fracaso", "No sé cómo empezar", "Nada"]', '["Lack experience", "Lack education", "Lack opportunities", "Fear of failure", "Don''t know how to start", "Nothing"]', 2, 30);

-- ✨ ESPIRITUAL (8)
INSERT INTO assessment_questions (pillar, question_text, question_text_en, question_type, options, options_en, weight, sort_order) VALUES
('spiritual', '¿Cómo describes tu espiritualidad?', 'How do you describe your spirituality?', 'single_choice', '["Cristiano (oración)", "Católico", "Otra religión", "Espiritual no religioso", "Meditación secular", "Conexión naturaleza", "Filosofía vida", "No prácticas", "Explorando"]', '["Christian (prayer)", "Catholic", "Other religion", "Spiritual not religious", "Secular meditation", "Nature connection", "Life philosophy", "No practices", "Exploring"]', 3, 31),
('spiritual', '¿Frecuencia de actividades espirituales?', 'Frequency of spiritual activities?', 'single_choice', '["Nunca", "Ocasionalmente", "Semanalmente", "Varias veces/semana", "Diariamente"]', '["Never", "Occasionally", "Weekly", "Several times/week", "Daily"]', 2, 32),
('spiritual', '¿Qué prácticas realizas?', 'What practices do you do?', 'multiple_choice', '["Oración", "Lectura textos sagrados", "Asistencia iglesia", "Meditación", "Mindfulness", "Journaling", "Tiempo naturaleza", "Gratitud", "Ninguna"]', '["Prayer", "Reading sacred texts", "Church attendance", "Meditation", "Mindfulness", "Journaling", "Time in nature", "Gratitude", "None"]', 2, 33),
('spiritual', '¿Cómo calificarías tu bienestar emocional?', 'How would you rate your emotional wellbeing?', 'slider', null, null, 3, 34),
('spiritual', '¿Con qué frecuencia te sientes estresado?', 'How often do you feel stressed?', 'single_choice', '["Todo el tiempo", "Muy frecuente", "A veces", "Raramente", "Casi nunca"]', '["All the time", "Very frequently", "Sometimes", "Rarely", "Almost never"]', 2, 35),
('spiritual', '¿Sientes que tu vida tiene propósito?', 'Do you feel your life has purpose?', 'single_choice', '["Para nada", "Muy poco", "Algo", "Bastante", "Totalmente"]', '["Not at all", "Very little", "Somewhat", "Quite a bit", "Completely"]', 3, 36),
('spiritual', '¿En qué áreas quieres crecer?', 'In which areas do you want to grow?', 'multiple_choice', '["Fe/Conexión", "Paz interior", "Gratitud", "Perdón", "Paciencia", "Propósito", "Manejo estrés", "Autoconocimiento", "Comunidad"]', '["Faith/Connection", "Inner peace", "Gratitude", "Forgiveness", "Patience", "Purpose", "Stress management", "Self-awareness", "Community"]', 2, 37),
('spiritual', '¿Qué obstáculos enfrentas?', 'What obstacles do you face?', 'multiple_choice', '["Falta tiempo", "Dudas", "No tengo comunidad", "Heridas pasado", "Distracciones", "No sé empezar", "Ninguno"]', '["Lack time", "Doubts", "No community", "Past wounds", "Distractions", "Don''t know how to start", "None"]', 2, 38);

-- 🎨 CREATIVO (7)
INSERT INTO assessment_questions (pillar, question_text, question_text_en, question_type, options, options_en, weight, sort_order) VALUES
('creative', '¿Practicas alguna actividad creativa?', 'Do you practice any creative activity?', 'multiple_choice', '["Música", "Arte/Dibujo", "Escritura", "Fotografía", "Diseño", "Cocina", "Crafts/DIY", "Ninguna"]', '["Music", "Art/Drawing", "Writing", "Photography", "Design", "Cooking", "Crafts/DIY", "None"]', 2, 39),
('creative', '¿Frecuencia de hobbies creativos?', 'Frequency of creative hobbies?', 'single_choice', '["Nunca", "Pocas veces/mes", "Una vez/semana", "Varias veces/semana", "Diariamente"]', '["Never", "Few times/month", "Once/week", "Several times/week", "Daily"]', 2, 40),
('creative', '¿Qué tan satisfecho estás con tu expresión creativa?', 'How satisfied are you with your creative expression?', 'slider', null, null, 2, 41),
('creative', '¿Te gustaría aprender alguna disciplina creativa?', 'Would you like to learn any creative discipline?', 'single_choice', '["No me interesa", "Tengo curiosidad", "Sí, intentarlo", "Sí, es prioridad", "Ya trabajo en ello"]', '["Not interested", "I''m curious", "Yes, try it", "Yes, it''s priority", "Already working on it"]', 1, 42),
('creative', '¿Qué te impide ser más creativo?', 'What prevents you from being more creative?', 'multiple_choice', '["Falta tiempo", "Falta habilidad", "Miedo juicio", "No sé empezar", "Falta inspiración", "Nada"]', '["Lack time", "Lack skill", "Fear judgment", "Don''t know how to start", "Lack inspiration", "Nothing"]', 2, 43),
('creative', '¿Disfrutas probar cosas nuevas?', 'Do you enjoy trying new things?', 'single_choice', '["Para nada", "No mucho", "A veces", "Frecuentemente", "Me encanta"]', '["Not at all", "Not much", "Sometimes", "Frequently", "I love it"]', 1, 44),
('creative', '¿Qué áreas creativas explorarías?', 'What creative areas would you explore?', 'multiple_choice', '["Música", "Arte visual", "Escritura", "Fotografía", "Video", "Diseño gráfico", "Cocina gourmet", "Otro"]', '["Music", "Visual art", "Writing", "Photography", "Video", "Graphic design", "Gourmet cooking", "Other"]', 1, 45);
